
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: flutter -v build apk --debug
